### ISSUE TITLE
How to avoid duplicate entries for same table in objects table?

### ISSUE THREAD

**Issue by nimearo** [keif888/SQLServerMetadata#23]
When SSIS project folders and databases are analyzed two entries are saved to dbo.objects table for the same database object.

It looks like table from SSIS package does not contains [dbo] schema in the name column and the corresponding entry from database analysis seems to contain [dbo] schema.  In consequence the relationships before my object from "Relational databases" can't be displayed in the "Dependency Viewer". I can see two entries with different IDs in SSISMeta dbo.objects table.

How can this be avoided?

**Comment by nimearo** [comment]
I debugged this a little bit more and can add that my dataflows from existing packages sometimes only contain the table name without the schema prefix in the OpenRowSet XML element for destination and source components.
Perhaps this is a legacy from previous SSDT versions because when I relink the table in SSDT designer and save my package it then contains the schema prefix. After that the dependency is correctly displayed in "Dependency Viewer" because I now only have one entry in SSISMeta.dbo.objects table

**Comment by keif888** [comment]
Underlying cause is the handling of connection managers that do not have a query defined, just a table name.  The raw table name is stored into the repository,  This is different to query based ones, where the query is parsed, and the missing schema qualifier (assumed to be dbo) is appended to the table name.  EnumerateComponentConnections within SsisEnumerator.cs is where the issue is.
I'll work out a fix later today.
